<script>
	import BannerMe from '$lib/components/landing/BannerMe.svelte';
	import { T, getTranslate } from '@tolgee/svelte';
	const { t } = getTranslate();
</script>

<div
	class="rel transform:rotate(2deg):hover_.codeimg1 transform:rotate(7deg):hover_.codeimg2 transform:rotate(12deg):hover_.codeimg3
	transform:translate(0,-20px)rotate(55deg):hover_.orangeShape transform:translate(0,-20px)rotate(55deg):hover_.orangeShape
	transform:translate(-20px,-17px):hover_.cyanShape
	transform:translate(20,-80)rotate(-15deg):hover_.crimsonShape
	rtr:50:hover_.crimsonShape
	rtl:100:hover_.crimsonShape
	rbl:15:hover_.orangeShape
	transform:translate(-50,-42)rotate(-50deg):hover_.blueShape
	rtl:45:hover_.blueShape
	opacity:1:hover_.greenShape
	r:100:hover_.greenShape

	"
>
	<div
		id="test"
		class="rel bg:rgb(23,33,45) p:20|20|20|20 p:40|0|0|40@sm p:60|0|0|60@lg overflow-x:clip"
	>
		<div class="flex gap:50 h:420">
			<div class="m:0|0|0|0 pr:100@sm w:full">
				<h1 class="f:bold f:30 f:40@sm f:60@md">
					<T keyName="hello_world" defaultValue="Hello, world" />! <br /><span
						class="f:40 f:50@sm f:70@md"><T keyName="i_am" defaultValue="I'm" /> Oskar,</span
					>
				</h1>
				<p>
					<T
						keyName="landing_hello_world_hero"
						defaultValue="an aspiring web developer on a mission to conquer the digital landscape. Fueled by
					curiosity and a hunger for growth, I am constantly exploring new technologies and
					techniques to sharpen my skills. While my portfolio may be modest for now, my
					determination and passion speak volumes. Stick around, witness my journey, and let's
					connect – we might just collaborate on something extraordinary!"
					/>
				</p>
			</div>

			<BannerMe class="banner hidden block@sm  " />
		</div>
	</div>
</div>

<div class=" mt:20 bg:green w:full h:300 z:90">Test</div>
<div class=" mt:20 bg:red w:full h:300 z:90">Test</div>
<div class=" mt:20 bg:blue w:full h:300 z:90">Test</div>

<!-- <T keyName="key" defaultValue="This is default" />
	
	OR
	
	{$t('this_is_a_key')} -->
<style>
	/* ----------------------------------------------
 * Generated by Animista on 2023-4-29 21:57:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation bounce-top
 * ----------------------------------------
 */
	@-webkit-keyframes bounce {
		0% {
			-webkit-transform: translateY(-45px);
			transform: translateY(-45px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
			opacity: 1;
		}
		24% {
			opacity: 1;
		}
		40% {
			-webkit-transform: translateY(-24px);
			transform: translateY(-24px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		65% {
			-webkit-transform: translateY(-12px);
			transform: translateY(-12px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		82% {
			-webkit-transform: translateY(-6px);
			transform: translateY(-6px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		93% {
			-webkit-transform: translateY(-4px);
			transform: translateY(-4px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		25%,
		55%,
		75%,
		87% {
			-webkit-transform: translateY(0px);
			transform: translateY(0px);
			-webkit-animation-timing-function: ease-out;
			animation-timing-function: ease-out;
		}
		100% {
			-webkit-transform: translateY(0px);
			transform: translateY(0px);
			-webkit-animation-timing-function: ease-out;
			animation-timing-function: ease-out;
			opacity: 1;
		}
	}
	@keyframes bounce {
		0% {
			-webkit-transform: translateY(-45px);
			transform: translateY(-45px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
			opacity: 1;
		}
		24% {
			opacity: 1;
		}
		40% {
			-webkit-transform: translateY(-24px);
			transform: translateY(-24px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		65% {
			-webkit-transform: translateY(-12px);
			transform: translateY(-12px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		82% {
			-webkit-transform: translateY(-6px);
			transform: translateY(-6px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		93% {
			-webkit-transform: translateY(-4px);
			transform: translateY(-4px);
			-webkit-animation-timing-function: ease-in;
			animation-timing-function: ease-in;
		}
		25%,
		55%,
		75%,
		87% {
			-webkit-transform: translateY(0px);
			transform: translateY(0px);
			-webkit-animation-timing-function: ease-out;
			animation-timing-function: ease-out;
		}
		100% {
			-webkit-transform: translateY(0px);
			transform: translateY(0px);
			-webkit-animation-timing-function: ease-out;
			animation-timing-function: ease-out;
			opacity: 1;
		}
	}
</style>
